name: Publish Docker Images

on:
  push:
    branches: [ master, zeek-v4 ]
    paths:
      # Paths that trigger a docker image build
      - '.github/workflows/docker-build.yml'
      - 'etc/**'
      - 'share/**'
      - 'docker-entrypoint.sh'
      - 'Dockerfile'

jobs:
  build:
    name: Build Zeek release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ["linux/amd64", "linux/arm64", "linux/arm/v7"]
        version: 
          # - "3.0.12"
          # - "3.2.4"
          - "4.0.5"
          - "4.2.0"
        include:
          # - version: "3.2.4"
          #   af-packet: "2.1.2"
          #   zkg: "2.7.1"
          #   tag: v3-latest
          # - version: "3.0.12"
          #   af-packet: "2.1.2"
          #   zkg: "2.7.1"
          #   tag: v3-lts
          - version: "4.2.0"
            af-packet: "3.0.2"
            zkg: "2.12.0"
            tag: latest
          - version: "4.0.5"
            af-packet: "3.0.2"
            zkg: "2.12.0"
            tag: lts

    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v2
    - 
      name: Set up QEMU # used for arm64 builds
      uses: docker/setup-qemu-action@v1
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - 
      name: Parse semver string # allows multiple docker tags like 3.0.0, 3.0, and 3
      id: semver_parser 
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: "${{ matrix.version }}"
    -
      name: Prepare docker tags  # allows multiple docker tags like 3.0.0, 3.0, and 3
      id: prep
      run: |
        DOCKER_IMAGE=activecm/zeek
        # e.g. lts or latest
        TAGS="${DOCKER_IMAGE}:${{ matrix.tag }}"
        if [[ "${{ matrix.tag }}" =~ "lts" ]]; then
          # e.g. 3
          TAGS="$TAGS,${DOCKER_IMAGE}:${{ steps.semver_parser.outputs.major }}"
        fi
        # e.g. 3.0
        TAGS="$TAGS,${DOCKER_IMAGE}:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}"
        # e.g. 3.0.0
        TAGS="$TAGS,${DOCKER_IMAGE}:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}"
        # make tags available to other actions steps as ${{ steps.prep.outputs.tags }}
        echo ::set-output name=tags::${TAGS}
    -
      name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.version }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: ${{ matrix.arch }}
        tags: ${{ steps.prep.outputs.tags }}
        build-args: |
          ZEEK_VERSION=${{ matrix.version }}
          AF_PACKET_VERSION=${{ matrix.af-packet }}
          ZKG_VERSION=${{ matrix.zkg }}
        push: false
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
